export const navbarLinks = [
  { name: "Home", href: "/" },
  {
    name: "sex toys",
    href: "/about",
    options: [
      {
        name: "Sex Toys for ladies",
        href: "/toy 1",
        options: [
          { name: "Nipple Viberators" },
          { name: "Standard Vibrators" },
          { name: "Other Style Vibrators" },
          { name: "Wand Massagers and Attachments" },
          { name: "Orgasm Balls" },
          { name: "Female Pumps" },
          { name: "Bunny Vibrators" },
          { name: "Duo Penetrator" },
          { name: "Clitoral Vibrators and Stimulators" },
          { name: "Fingers Vibrators" },
          { name: "Vibrators With Clit Stims" },
          { name: "Mini Vibrators" },
          { name: "G-Spot Vibrators" },
          { name: "Vibrating Eggs" },
          { name: "Remote Control Toys" },
          { name: "Kegel Exercise" },
        ],
      },
      {
        name: "Sex toys for men",
        href: "/toy 1",
        options: [
          { name: "Vibrating Masturbators" },
          { name: "Love Ring Vibrators" },
          { name: "Realistic Masturbators" },
          { name: "Penis Enlargers" },
          { name: "Vibrating Vaginas" },
          { name: "Fleshlight Range" },
          { name: "Penis Sleeves" },
          { name: "Penis Entenders" },
          { name: "Masturbators" },
          { name: "Love Rings" },
        ],
      },
      {
        name: "Realistic Dildos and vibes",
        href: "/toy 1",
        options: [
          { name: "Strap on Dildo" },
          { name: "Realistic Vibrators" },
          { name: "Penis Vibrators" },
          { name: "Squirting Dildos" },
          { name: "Penis Dildo" },
          { name: "Mould your own kits" },
          { name: "Realistic Dildos" },
          { name: "Strapless Strap Ons" },
          { name: "Vibrating Strap Ons" },
          { name: "Hollow Strap Ons" },
          { name: "Strap On Harnesses" },
        ],
      },
      {
        name: "Sex Dolls",
        href: "/toy 1",
        options: [{ name: "Male Love Dolls" }, { name: "Female Love Dolls" }],
      },
      {
        name: "Glass",
        href: "/toy 1",
      },
      {
        name: "Sex Kits",
        href: "/toy 1",
      },
      {
        name: "Other Dildos",
        href: "/toy 1",
      },
    ],
  },
  {
    name: "BONDAGE GEAR",
    href: "/services",
    options: [
      { name: "Bondage Kits" },
      { name: "Nipple Clamps" },
      { name: "Fetish Fantasy Series" },
      { name: "Paddles" },
      { name: "Bondage Hoods" },
      { name: "PVC Orgy Bdding" },
      { name: "Medical Instruments" },
      { name: "Cock and Ball Bondage" },
      { name: "Handcuffs" },
      { name: "Electro Sex Stimulation" },
      { name: "Large Accessories" },
      { name: "Male Chastity" },
      { name: "Whips" },
      { name: "Bondage Cock Rings" },
      { name: "Masks" },
      { name: "Restraints" },
      { name: "Collars" },
      { name: "Gags and Bits" },
    ],
  },
  {
    name: "ANAL RANGE",
    href: "/contact",
    options: [
      { name: "Anal Beads" },
      { name: "Butt Plug Kits" },
      { name: "Jewel Butt Plugs" },
      { name: "Butt Plugs" },
      { name: "Vibrating Buttplug" },
      { name: "Tunnel and Stretchers" },
      { name: "Anal Inflatables" },
      { name: "Tail Butt Plugs" },
      { name: "Prostate Massagers" },
      { name: "Anal Probes" },     
    ],
  },
  {
    name: "CLOTHES",
    href: "/clothes",
    options: [
      { name: "Stockings" },
      { name: "Accessories" },
      { name: "Plus Size Lingerie" },
      { name: "Bra Sets" },
      { name: "Leather" },
      { name: "Bodies and Playsuits" },
      { name: "Babydolls" },
      { name: "Basques and Corsets" },
      { name: "Sexy Briefs" },
      { name: "Body Jewellery" },
      { name: "Latex" },
      { name: "Fantasy" },
      { name: "Dresses and Chemises" },
    ],
  },
  {
    name: "RELAXATION ZONE",
    href: "/relaxation-zone",
    options: [
      { name: "Flavoured Lubricants and Oils" },
      { name: "Lubricants and Oils" },
      { name: "Anal Lubricants" },
      { name: "Baths and Massage" },
      { name: "Kama Sutra" },
      { name: "Edible Treats" },
      { name: "Condoms" },
      { name: "Personal Hygiene" },
    ],
  },
  {
    name: "NOVELTIES",
    href: "/novelties",
    options: [
      { name: "Hen And Stag Nights" },
      { name: "Games" },
      { name: "Media" },
    ],
  },
];
 